name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta todos los días a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: poncho-ajmv
          outputs: |
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the snake SVG to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate GitHub contribution grid snake"
        env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

