name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta todos los días a medianoche
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: poncho-ajmv
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Push to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake contribution graph"
